version: 0.2

env:
  variables:
    PYTHONUNBUFFERED: "1"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "[install] Python version"
      - python --version
      - echo "[install] Upgrading pip and installing dependencies"
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt



artifacts:
  files:
    - Dockerfile
    - entrypoint.sh
    - requirements.txt
    - run.py
    - README.md
    - app/**/*
    - scripts/**/*
    - .dockerignore
    - .ebignore

cache:
  paths:
    - /root/.cache/pip/**/*
